ci: do use "python -m pip" instead of just "pip"
ATM it fails as

pip install --upgrade pip
Requirement already satisfied: pip in c:\python39-x64\lib\site-packages
(23.2.1)
Collecting pip
  Obtaining dependency information for pip from
https://files.pythonhosted.org/packages/d4/55/90db48d85f7689ec6f81c0db0622d704306c5284850383c090e6c7195a5c/pip-24.2-py3-none-any.whl.metadata
  Downloading pip-24.2-py3-none-any.whl.metadata (3.6 kB)
Downloading pip-24.2-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 1.8/1.8 MB 10.5 MB/s eta
0:00:00
ERROR: To modify pip, please run the following command:
C:\Python39-x64\python.exe -m pip install --upgrade pip
[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip
Command exited with code 1